info:
  namespace: betterranks
font_images:
  admin:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "admin.png"
    scale_ratio: 9
    y_position: 8
  mod:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "mod.png"
    scale_ratio: 9
    y_position: 8
  helper:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "helper.png"
    scale_ratio: 9
    y_position: 8
  player:
    permission: "betterranks.player"
    show_in_gui: true
    suggest_in_command: false
    path: "player.png"
    scale_ratio: 9
    y_position: 8
  builder:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "builder.png"
    scale_ratio: 9
    y_position: 8
  youtube:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "youtube.png"
    scale_ratio: 9
    y_position: 8
  patreon:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "patreon.png"
    scale_ratio: 9
    y_position: 8
  patreon2:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "patreon2.png"
    scale_ratio: 9
    y_position: 8
  java:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "java.png"
    scale_ratio: 9
    y_position: 8
  skript:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "skript.png"
    scale_ratio: 9
    y_position: 8
  developer:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "developer.png"
    scale_ratio: 9
    y_position: 8
  dev:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "dev.png"
    scale_ratio: 9
    y_position: 8
  vip:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "vip.png"
    scale_ratio: 9
    y_position: 8
  vipplus:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "vipplus.png"
    scale_ratio: 9
    y_position: 8
  modo:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "modo.png"
    scale_ratio: 9
    y_position: 8
  event:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "event.png"
    scale_ratio: 9
    y_position: 8
  rejoindre:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "rejoindre.png"
    scale_ratio: 9
    y_position: 8
  discord:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "discord.png"
    scale_ratio: 9
    y_position: 8
  game:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "game.png"
    scale_ratio: 9
    y_position: 8
  modo_test:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "modo_test.png"
    scale_ratio: 9
    y_position: 8
  manager:
    permission: "betterranks.admin"
    show_in_gui: true
    suggest_in_command: false
    path: "manager.png"
    scale_ratio: 9
    y_position: 8